from __future__ import annotations

from pathlib import Path

from check_synthetic_proof import _assert_public_manifest
from synthetic_proof import run_synthetic_proof

REPO_ROOT = Path(__file__).resolve().parents[1]
OUTCOME_DIR = REPO_ROOT / "outputs" / "release-review-dry-run"
OUTCOME_FILE = OUTCOME_DIR / "release-review-outcome.md"
PROOF_NAME = "release-review-dry-run"


def main() -> None:
    manifest = run_synthetic_proof(proof_name=PROOF_NAME, emit=False)
    _assert_public_manifest(manifest)
    OUTCOME_DIR.mkdir(parents=True, exist_ok=True)
    OUTCOME_FILE.write_text(_render_outcome(manifest), encoding="utf-8")
    print(f"Wrote public-safe release review outcome to {OUTCOME_FILE.relative_to(REPO_ROOT)}")


def _render_outcome(manifest: dict[str, object]) -> str:
    operations = manifest["operations"]
    if not isinstance(operations, list):
        raise AssertionError("Synthetic proof operations must be a list.")

    operation_lines = "\n".join(
        f"- {operation['operation']}: {len(operation['files'])} public-safe output file(s)"
        for operation in operations
        if isinstance(operation, dict)
    )

    return f"""# Pagewright Release Review Outcome

Generated by `examples/generate_release_review_outcome.py`.

This dry-run outcome is public-safe evidence only. It does not create, tag, or publish a release.
It is local-only evidence under ignored `outputs/{PROOF_NAME}`.
Paste only sanitized summaries into public issues or PRs.

## Review Target

- Commit or range: TODO
- Reviewer: TODO
- Date: TODO
- GitHub Actions CI run URL: TODO

## Required Check Results

- Ruff: TODO
- Pytest: TODO
- Synthetic proof check: passed for generated proof manifest
- Public readiness check: TODO
- Secret-pattern scan: TODO
- GitHub Actions CI: TODO

## Synthetic Proof Summary

- Proof source: generated synthetic inputs from `app/pdf_forge_api/demo.py`
- Sanitized examples only: yes
- Operations covered:
{operation_lines}

## Public-Safe Proof Outcome

- Proof outputs checked: yes
- No private PDFs in proof outputs: confirmed by synthetic proof path
- No real user documents in proof outputs: confirmed by generated inputs only
- No local absolute paths in proof outputs: confirmed by public manifest check
- No secrets, credentials, tokens, private URLs, or proprietary data in proof outputs:
  confirmed by public manifest check
- Ignored proof folders remain uncommitted: outputs are written under ignored `outputs/{PROOF_NAME}`
- Public sharing rule: paste only sanitized summaries into public issues or PRs

## Storage and Compatibility Outcome

- D-drive storage assumptions reviewed: TODO
- Internal compatibility package name `pdf_forge` preserved: TODO
- Internal compatibility package name `pdf_forge_api` preserved: TODO
- CLI compatibility command `pdf-forge` preserved: TODO

## Notes

TODO: Keep notes public-safe. Do not include private PDFs, local absolute paths, secrets,
credentials, tokens, private URLs, proprietary data, or sensitive implementation details.
"""


if __name__ == "__main__":
    main()
