from __future__ import annotations

import json
import shutil
from pathlib import Path
from typing import Any

from fastapi.testclient import TestClient
from pdf_forge_api.main import OPERATIONS, create_app
from pdf_forge_api.storage import StoragePaths

PROOF_NAME = "public-proof"
MANIFEST_FILE = "public-proof-manifest.json"


def main() -> None:
    run_synthetic_proof()


def run_synthetic_proof(proof_name: str = PROOF_NAME, emit: bool = True) -> dict[str, Any]:
    repo_root = Path(__file__).resolve().parents[1]
    paths = StoragePaths(
        repo_root=repo_root,
        scratch_dir=repo_root / "scratch" / proof_name,
        outputs_dir=repo_root / "outputs" / proof_name,
    )
    _reset_proof_dirs(repo_root, [paths.scratch_dir, paths.outputs_dir], proof_name)
    paths.ensure()

    client = TestClient(create_app(paths))
    operations: list[dict[str, Any]] = []

    for operation in OPERATIONS:
        response = client.post(f"/jobs/demo/{operation}")
        response.raise_for_status()
        data = response.json()
        operations.append(_summarize_job(data))

    manifest = {
        "proof": "Pagewright synthetic public demo",
        "privacy": "synthetic inputs generated by app/pdf_forge_api/demo.py; no user documents",
        "operations": operations,
    }
    manifest_path = paths.outputs_dir / MANIFEST_FILE
    manifest_path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    if emit:
        print(json.dumps(manifest, indent=2))
    return manifest


def _reset_proof_dirs(repo_root: Path, targets: list[Path], proof_name: str) -> None:
    resolved_root = repo_root.resolve()
    for target in targets:
        resolved_target = target.resolve()
        if not resolved_target.is_relative_to(resolved_root):
            raise RuntimeError(f"Refusing to clear path outside repo: {resolved_target}")
        if resolved_target.name != proof_name:
            raise RuntimeError(f"Refusing to clear unexpected proof path: {resolved_target}")
        if resolved_target.exists():
            shutil.rmtree(resolved_target)


def _summarize_job(data: dict[str, Any]) -> dict[str, Any]:
    files = data["files"]
    bundle = data.get("bundle")
    summary: dict[str, Any] = {
        "operation": data["operation"],
        "files": [
            {
                "file_name": file["file_name"],
                "size_bytes": file["size_bytes"],
            }
            for file in files
        ],
    }
    if bundle:
        summary["bundle"] = {
            "file_name": bundle["file_name"],
            "size_bytes": bundle["size_bytes"],
            "file_count": bundle["file_count"],
        }
    return summary


if __name__ == "__main__":
    main()
